services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\JavaScriptContext\:
        resource: '../../*'

    Becklyn\JavaScriptContext\Context\JavaScriptContext:
        $providers: !tagged javascript_context.provider
